trigger:
  - main

pool:
  vmImage: ubuntu-latest

variables:
  - group: DockerTest
  - name: resourceGroupName
    value: DockerDeployTestRG
  - name: location
    value: westeurope
  - name: imageWebApiName
    value: webapidockertest

steps:
  - task: AzureCLI@2
    displayName: Create Resource Group
    inputs:
      azureSubscription: $(lib-subscriptionConn)
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        az group create --name $(resourceGroupName) --location $(location)
  - task: AzureCLI@2
    displayName: Create Resources
    inputs:
      azureSubscription: $(lib-subscriptionConn)
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        az deployment group create \
        --resource-group $(resourceGroupName) \
        --template-file infrastructure/main.bicep \
        --parameters location=$(location) imageWebApiName=$(imageWebApiName)

    # - pwsh: ./Infrastructure/deploy.ps1
    #   displayName: 'Run infrastructure script'

# - script: . 'Infrastructure/deploy.ps1'
#   displayName: 'Run infrastructure script'

