trigger:
  - main

pool:
  vmImage: ubuntu-latest

variables:
  - name: subscriptionConn
  - name: resourceGroupName
    value: DockerDeployTestRG
  - name: location
    value: westeurope

steps:
  - task: AzureCLI@2
    displayName: Create Resource Group
    inputs:
      azureSubscription: $(subscriptionConn)
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        az group create --name $(resourceGroupName) --location $(location)

    # - pwsh: ./Infrastructure/deploy.ps1
    #   displayName: 'Run infrastructure script'

# - script: . 'Infrastructure/deploy.ps1'
#   displayName: 'Run infrastructure script'

