# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Infrastructure
  displayName: Infrastructure
  jobs:
  - job: ResourceGroup
    displayName: Create Resource Group
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - powershell: Get-ChildItem -Path 'Insert root path' -recurse
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/WebAPI/Dockerfile'
        tags: |
          $(tag)

