trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
  - pwsh: ./Infrastructure/deploy.ps1
    displayName: 'Run infrastructure script'
# - script: . 'Infrastructure/deploy.ps1'
#   displayName: 'Run infrastructure script'

