name: $(date:yyyyMMdd)$(rev:.r)
trigger:
  branches:
    include:
      - main
  paths:
    include:
      - WebApi

variables:
- group: DockerTest

jobs:
- job: WebApiDocker
  displayName: Docker
  pool:
    vmImage: ubuntu-latest
  steps:
  - checkout: self
    clean: true
    fetchTags: false
  - task: Docker@0
    displayName: Build an image
    inputs:
      azureSubscription: $(lib-azureSubscriptionConnName)
      azureContainerRegistry: $(lib-azureContainerRegistryConn)
      dockerFile: WebAPI/Dockerfile
      imageName: WebAPI:$(Build.BuildId)
      includeLatestTag: true
      buildArguments:  >-
        fNameArg=John

        lNameArg=Doe

        emailArg=john.doe@email.com
  - task: Docker@0
    displayName: Push an image
    inputs:
      azureSubscription: $(lib-azureSubscriptionConnName)
      azureContainerRegistry: $(lib-azureContainerRegistryConn)
      action: Push an image
      imageName: WebAPI:$(Build.BuildId)
      includeLatestTag: true
  - pwsh: |    
      $FIRST_NAME="John"
      $LAST_NAME="Doe"
      $EMAIL="john.doe@email.com"

