trigger:
  - main

pool:
  vmImage: ubuntu-latest

variables:
  - group: DockerTest
  - name: resourceGroupName
    value: DockerDeployTestRG
  - name: location
    value: westeurope
  - name: imageWebApiName
    value: webapidockertest

steps:
  - task: Docker@2
    displayName: Build and push an image to container registry
    inputs:
      command: buildAndPush
      repository: $(imageWebApiName)
      dockerfile: "$(Build.SourcesDirectory)/WebAPI/Dockerfile"
      containerRegistry: $(lib-dockerRegistryServiceConn)
      tags: |
        latest
